### ISSUE TITLE
Securize removing data folder

### ISSUE THREAD

**Issue by frinux** [samdoran/ansible-role-pgsql-replication#12]
https://github.com/samdoran/ansible-role-pgsql-replication/blob/ae7bc9bd6ebfbdc32925e53fae36b7a5e522130f/tasks/replica.yml#L7

This line is very dangerous: depending on variable pgsqlrep_data_path, it could delete the whole filesystem!
You should test whether pgsqlrep_data_path is defined and not empty, for instance with:

```
- name: Clear out data directory
  shell: rm -rf {{ pgsqlrep_data_path }}/*
  when: pgsqlrep_data_path is defined and pgsqlrep_data_path|length > 0
```

**Comment by samdoran** [comment]
> This line is very dangerous: depending on variable pgsqlrep_data_path, it could delete the whole filesystem!

Very good point! I'll get this fixed. Thank you for pointing it out.
