### ISSUE TITLE
breaking changes in dependency - nginx role in Tower 3.6.1

### ISSUE THREAD

**Issue by gforster** [samdoran/ansible-role-pgsql-replication#13]
The nginx role was refactored and there are some issues with missing variables (web_server_ssl_cert/web_server_ssl_key, aw_group), directories (/etc/tower does not exist), etc. 

seems to be that the  `nginx_exec_vars_only` var is now meaningless (unused in the new nginx role).

**Comment by samdoran** [comment]
I'm not sure where this role is using `nginx` at all. This role has no dependencies and it is making no external calls to roles.

**Comment by samdoran** [comment]
I think this is referring to the example playbook that had the `nginx` role listed. I don't recall why that was in the example, but I have removed it.
