### ISSUE TITLE
nginx role fails when calling from ansible-role-pgsql-replication playbook

### ISSUE THREAD

**Issue by iamgini** [samdoran/ansible-role-pgsql-replication#14]
Thank you for sharing this role.

**Info:**
ansible 2.9.3
ansible tower 3.6.1
3x Ansible nodes
2x db node (1x master and 1x replica)
Tower is running fine.

**Issue:**
using `ansible-role-pgsql-replication` to enable streaming replication on replica node. (using sample playbook as used in repo) But playbook fails at nginx role.

```
TASK [nginx : place self-signed SSL certificates] ***********************************************************
fatal: [node05-db.lab.local]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'tower_cert'\n\nThe error appears to be in '/home/ansible/ansible-tower-setup-3.6.1-1/roles/nginx/tasks/tasks.yml': line 84, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - name: place self-signed SSL certificates\n          ^ here\n"}
```

**Observation**
- we are using `hosts: database_replica` in playbook (Hence the playbook will not consider any other hosts, that's fine). 
- But this will skip `- name: slurp self-signed SSL key` task because the node is not master node (`when: inventory_hostname == groups['tower'][0]`)
- and the `tower_cert` variable will be undefined because of that; hence next block will fail with undefined variable (`- name: Copy the cert we just created to additional hosts`)

Any workaround ?

Do we really need nginx on `database_replica` node ?

**Comment by ginigangadharan** [comment]
same for `install_postgres.yml` as well.
```
TASK [packages_el : Check for old Postgres data] ************************************************************
fatal: [node05-db.lab.local]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'existing_pg_dir' is undefined\n\nThe error appears to be in '/home/ansible/ansible-tower-setup-3.6.1-1/roles/packages_el/tasks/install_postgres.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Check for old Postgres data\n  ^ here\n"}
```

```
- name: Check for old Postgres data
  stat:
    path: "{{ existing_pg_dir }}/PG_VERSION"
  register: old_pg_version_file
```

**Comment by samdoran** [comment]
I don't see anywhere in the role tasks that call the `nginx` role. I don't think the `nginx` role is required on the replica. I'm not sure how any tasks in the role would be calling this role, though.

**Comment by iamgini** [comment]
@samdoran oh okay.
Sorry, I was following the same playbook you have mentioned in the repo README.md file. See screenshot.
![screen](https://user-images.githubusercontent.com/4469813/75504803-6fd07680-5a14-11ea-9766-7c75aeb5df0f.jpg)

(I can see, this is already updated in current README.md; thanks)

yes, I have commented out the same and run the playbook to proceed; and worked well (yeah after those tweaks I have mentioned in thread : https://github.com/samdoran/ansible-role-pgsql-replication/issues/15)

Thanks again for sharing such a role.

**Comment by samdoran** [comment]
Oh! That explains it. It's in the example playbook. 😄 

I don't remember why that was there originally. Probably needed some variable from the role in the subsequent roles. I'm trying to use those roles without modifying, and it is a bit difficult because they have some rather strange interdependencies.

**Comment by samdoran** [comment]
Closing since this was an issue with the example playbook not the role itself.

**Comment by iamgini** [comment]
@samdoran great. thank you :)
